name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description...
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Reproduction steps...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Select platform
      description: Choose the platform on which the bug occurs.
      options:
        - iOS
        - Android
        - Web
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Screenshots:
        Attachments can be provided upon request.
